import { Assign } from '../../types';
import { getRandomId } from '../../utils/random';
import { TSequence } from '../Sequence/def';
import { TDiseaseSymptom, TDiseaseSymptomID } from './def';

export const getSeedSymptoms = (sequences: TSequence[]) => {
    const list = Symptoms.map((name, i) =>
        createDiseaseSymptom({
            id: name as TDiseaseSymptomID,
            name,
            sequence: sequences[i],
        }),
    );

    return { sequences, list };
};

export function createDiseaseSymptom(
    symptom: Assign<TDiseaseSymptom, { id?: TDiseaseSymptomID }>,
): TDiseaseSymptom {
    return {
        id: getRandomId() as TDiseaseSymptomID,
        ...symptom,
    };
}

const Symptoms = [
    'a bad taste in mouth',
    'a dry mouth',
    'a dry skin',
    'a fever',
    'a loss of appetite',
    'a loss of taste',
    'a metallic taste in mouth',
    'a rash',
    'a runny nose',
    'a shortness of breath',
    'a skin bump outbreak',
    'a skin sore outbreak',
    'a sore throat',
    'a sore tongue',
    'abdominal pain',
    'acid reflux',
    'an altered mental status',
    'an itchy skin',
    'ankle pain',
    'arm pain',
    'back pain',
    'bad breath',
    'blistering',
    'blood in urine',
    'bloody nose',
    'blurred vision',
    'breast pain',
    'breathing difficulty',
    'burning urination',
    'chest pain',
    'chills',
    'cloudy urine',
    'cold feet',
    'cold fingers',
    'cold hands',
    'confusion',
    'constipation',
    'coughing',
    'cramping',
    'delirium',
    'delusion',
    'depression',
    'diarrhea',
    'dizziness',
    'double vision',
    'drooling',
    'ear pain',
    'easy bruising',
    'euphoria',
    'excess sweating',
    'excessive yawning',
    'eye discharge',
    'eye swelling',
    'eye twitching',
    'fainting',
    'feeling light-headed',
    'feeling sick',
    'feeling sleepy',
    'feeling tired',
    'feeling weak',
    'finger numbness',
    'frequent urination',
    'gum pain',
    'hair loss',
    'hallucination',
    'headache',
    'hearing difficulty',
    'heartburn',
    'hip pain',
    'hyperactivity',
    'inattention',
    'increased thirst',
    'jaw pain',
    'joint redness',
    'joint stiffness',
    'joint swelling',
    'knee pain',
    'leg pain',
    'leg swelling',
    'memory loss',
    'mood fluctuation',
    'mouth sores',
    'moving difficulty',
    'muscle cramps',
    'muscle weakness',
    'nail brittleness',
    'nasal congestion',
    'nausea',
    'neck pain',
    'peeing difficulty',
    'pelvic pain',
    'pupil dilation',
    'rectal pain',
    'red spot outbreak',
    'ringing ears',
    'seizures',
    'shaking hands',
    'shoulder pain',
    'sleeping difficulty',
    'sneezing',
    'swallowing difficulty',
    'temperature fluctuation',
    'temporary blindness',
    'tingling feet',
    'tingling hands',
    'toe numbness',
    'toothache',
    'vomiting',
    'walking difficulty',
    'weight gain',
    'weight loss',
];
